### ISSUE TITLE
Limit DB queries

### ISSUE THREAD

**Issue by maxdemaio** [maxdemaio/thelangbot#18]
Currently, for ever Twitter user in my list of tweets we query for their username in the DB.

Better idea:
- Query the DB once for blacklist/supporters 
```sql
SELECT * FROM example
```
- Turn query object into Python accessible object
- Check if in they are in that list

**Comment by Rairye** [comment]
So, this would affect the main and isBlacklist methods in bot.py, correct?

**Comment by Rairye** [comment]
Addition: I am not sure if you started working on this, but I threw together something at:
https://github.com/Rairye/thelangbot/blob/main/bot.py

Please note that it has been a while since I have looked at SQL. Also, I have not double checked the code yet.

Also, I did it just for the blacklist but I will add something for supporters.

**Comment by maxdemaio** [comment]
Hey @Rairye ! This looks actually exactly what we'd like to do. Getting them in a set would basically limit it to just 2 db queries per time we look for new tweets to retweet. I'm going to see if I can implement your code this weekend.

Testing is a little weird at the moment because we have to debug in production. I was thinking of creating a Markdown file soon on how to setup a test bot. This way we could test new code implementations w/o blasting things out on the main account 😆

**Comment by Rairye** [comment]
Thanks for the feedback. Should I go ahead and make a pull request. (I still haven't double checked the code. Also, I don't usually work with CRUD so I am not sure if my SQL is correct.

**Comment by maxdemaio** [comment]
Yes go right ahead with the PR 🚀  Basically just need to check that the SQL query is sanitized and works properly which I can double check on my end.

I have some basic test cases written but they mostly only work with Twitter bot secrets set up. Hopefully soon I'll forge a readme for making a test bot.

**Comment by maxdemaio** [comment]
Finalized with https://github.com/maxdemaio/thelangbot/pull/19
